#include <libultraship/libultraship.h>
#include "2s2h/GameInteractor/GameInteractor.h"
#include "2s2h/ShipInit.hpp"

#include "2s2h/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
// Think we should we put both Spider houses in the same file?
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM] = RandoRegion{ .name = "Central Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_BEHIND_SKULL_1, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_BEHIND_SKULL_2, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_CEILING_PLANK, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_CEILING_EDGE, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_WEBBED_HOLE, CAN_LIGHT_TORCH_NEAR_ANOTHER && HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_UPPER_POT, true),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_LOWER_POT, true),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_WEBBED_POT, CAN_LIGHT_TORCH_NEAR_ANOTHER),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_JAR, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_MAIN_ROOM_1, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_MAIN_ROOM_2, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_MAIN_ROOM_WEB, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_MAIN_ROOM_BOE, true),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_ENTRANCE_LOWER, HAS_ITEM(ITEM_HOOKSHOT)),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_LIBRARY_ROOM, CAN_LIGHT_TORCH_NEAR_ANOTHER),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_MEETING_ROOM, true),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_STORAGE_ROOM, CAN_LIGHT_TORCH_NEAR_ANOTHER)
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_ENTRANCE_LOWER] = RandoRegion{ .name = "Entrance Lower", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_ENTRANCE_LEFT_WALL, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA || (CAN_USE_PROJECTILE && CAN_BE_GORON)),
            CHECK(RC_OCEAN_SKULLTULA_ENTRANCE_RIGHT_WALL, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_ENTRANCE_WEB, HAS_ITEM(ITEM_BOW) && HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_ENTRANCE_1, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_ENTRANCE_2, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_ENTRANCE_3, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_ENTRANCE_4, true)
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_ENTRANCE_UPPER, CAN_BE_GORON),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, HAS_ITEM(ITEM_HOOKSHOT))
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_ENTRANCE_UPPER] = RandoRegion{ .name = "Entrance Upper", .sceneId = SCENE_KINDAN2,
        .checks = {
            // TODO : Add check for getting all of the Ocean Skulltula Tokens
        },
        .exits = { //     TO                                         FROM
            EXIT(ENTRANCE(GREAT_BAY_COAST, 8),          ENTRANCE(OCEANSIDE_SPIDER_HOUSE, 0), true)
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_ENTRANCE_LOWER, CAN_USE_EXPLOSIVE && CAN_BE_GORON),
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_LIBRARY_ROOM] = RandoRegion{ .name = "Library Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_HOLE_BEHIND_CABINET, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_PICTURE, CAN_USE_PROJECTILE),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_CEILING_EDGE, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_PICTURE, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_ON_CORNER_BOOKSHELF, true),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_BOOKCASE_1, true),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_BOOKCASE_2, true),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, true)
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_MEETING_ROOM] = RandoRegion{ .name = "Meeting Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CEILING_EDGE, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CHANDELIER_1, true),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CHANDELIER_2, true),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CHANDELIER_3, true),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_POT, true),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_BEHIND_PICTURE, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SPIDER_HOUSE_CHEST_HP, HAS_ITEM(ITEM_BOW) && HAS_ITEM(ITEM_MASK_CAPTAIN)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_COLORED_SKULLS_1, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_COLORED_SKULLS_2, true),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, true)
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_STORAGE_ROOM] = RandoRegion{ .name = "Storage Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_BEHIND_BOAT, true),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_BEHIND_CRATE, HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_CEILING_WEB, CAN_USE_MAGIC_ARROW(FIRE) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_CRATE, true),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_JAR, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_1, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_2, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_3, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_4, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_TOP_1, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_TOP_2, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_POT_STORAGE_TOP_3, HAS_ITEM(ITEM_HOOKSHOT)),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, true)
        }
    };
}, {});
// clang-format on
