#ifndef RANDO_TYPES_H
#define RANDO_TYPES_H

typedef enum {
    RCTYPE_UNKNOWN,
    RCTYPE_CHEST,
    RCTYPE_FREESTANDING,
    RCTYPE_SKULL_TOKEN,
    RCTYPE_SHOP,
    RCTYPE_STRAY_FAIRY,
    RCTYPE_MAX,
} RandoCheckType;

typedef enum {
    RC_UNKNOWN,
    RC_S_CLOCK_TOWN_POH,
    RC_S_CLOCK_TOWN_UPPER_CHEST,
    RC_S_CLOCK_TOWN_CARPENTER_CHEST,
    RC_N_CLOCK_TOWN_POH,
    RC_E_CLOCK_TOWN_UPPER_CHEST,
    RC_LAUNDRY_DUDE,
    RC_CLOCK_TOWN_STRAY_FAIRY,
    RC_CLOCK_TOWN_GREAT_FAIRY,
    RC_STOCK_POT_INN_GRANDMA_SHORT_STORY,
    RC_STOCK_POT_INN_GRANDMA_LONG_STORY,
    RC_STOCK_POT_INN_ROOM_KEY,
    RC_WOODFALL_LOBBY_STRAY_FAIRY,
    RC_WOODFALL_LOBBY_CHEST_STRAY_FAIRY,
    RC_MAX,
} RandoCheck;

typedef enum {
    RI_UNKNOWN,
    RI_PIECE_OF_HEART,
    RI_CLOCK_TOWN_STRAY_FAIRY,
    RI_PROGRESSIVE_MAGIC,
    RI_GREEN_RUPEE,
    RI_BLUE_RUPEE,
    RI_RED_RUPEE,
    RI_PURPLE_RUPEE,
    RI_SILVER_RUPEE,
    RI_ROOM_KEY,
    RI_MASK_BREMEN,
    RI_WOODFALL_STRAY_FAIRY,
    RI_MAX,
} RandoItem;

typedef enum {
    RANDO_INF_CLOCK_TOWN_STRAY_FAIRY_COLLECTED,
    RANDO_INF_MAX,
} RandoInf;

#endif // RANDO_TYPES_H
